server:
  port: 8080

spring:
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin

logging:
  level:
    springbootjms:
      com:
        epam:
          dpikus:
            jms:
              impl: INFO

virtual-topic-example:
  topic: VirtualTopic.MY-SUPER-TOPIC





